[1] Add BFS
sofurihafe/high-performance-graph-analysis-course pull request #1
Opened 2023-03-11 23:52 UTC by sofurihafe

2023-03-14 09:53 UTC, rustam-azimov requested changes

2023-03-14 09:53 UTC, rustam-azimov commented on project/bfs.py
> +        visited.assign_scalar(value=True, mask=front)
Можно обойтись без visited. Останавливаемся когда front пустой. Вместо маски visited можно использовать answer.

2023-03-14 09:53 UTC, rustam-azimov commented on project/bfs.py
> +        front = front.vxm(matrix)
Лучше сразу здесь маску использовать, иначе лишнего считаем и лишние операции делаем.

2023-03-14 09:53 UTC, rustam-azimov commented on tests/test_bfs.py
> +    [
Лучше сразу реализуйте функции, которые считывают с файла граф и в нужный формат конвертируют.

2023-03-14 20:37 UTC, sofurihafe commented on project/bfs.py
> +        visited.assign_scalar(value=True, mask=front)
Done.

2023-03-18 06:54 UTC, rustam-azimov approved these changes
5 баллов

2023-03-19 01:35 UTC, merged